//! Port of `src/data_store_owners.cpp` — immutable store owner table.

use std::sync::LazyLock;

use crate::store::{Owner, MAX_OWNERS};

pub static STORE_OWNERS: LazyLock<[Owner; MAX_OWNERS as usize]> = LazyLock::new(|| {
    [
        Owner {
            name: "Erick the Honest       (Human)      General Store",
            max_cost: 250,
            max_inflate: 175,
            min_inflate: 108,
            haggles_per: 4,
            race: 0,
            max_insults: 12,
        },
        Owner {
            name: "Mauglin the Grumpy     (Dwarf)      Armory",
            max_cost: 32000,
            max_inflate: 200,
            min_inflate: 112,
            haggles_per: 4,
            race: 5,
            max_insults: 5,
        },
        Owner {
            name: "Arndal Beast-Slayer    (Half-Elf)   Weaponsmith",
            max_cost: 10000,
            max_inflate: 185,
            min_inflate: 110,
            haggles_per: 5,
            race: 1,
            max_insults: 8,
        },
        Owner {
            name: "Hardblow the Humble    (Human)      Temple",
            max_cost: 3500,
            max_inflate: 175,
            min_inflate: 109,
            haggles_per: 6,
            race: 0,
            max_insults: 15,
        },
        Owner {
            name: "Ga-nat the Greedy      (Gnome)      Alchemist",
            max_cost: 12000,
            max_inflate: 220,
            min_inflate: 115,
            haggles_per: 4,
            race: 4,
            max_insults: 9,
        },
        Owner {
            name: "Valeria Starshine      (Elf)        Magic Shop",
            max_cost: 32000,
            max_inflate: 175,
            min_inflate: 110,
            haggles_per: 5,
            race: 2,
            max_insults: 11,
        },
        Owner {
            name: "Andy the Friendly      (Halfling)   General Store",
            max_cost: 200,
            max_inflate: 170,
            min_inflate: 108,
            haggles_per: 5,
            race: 3,
            max_insults: 15,
        },
        Owner {
            name: "Darg-Low the Grim      (Human)      Armory",
            max_cost: 10000,
            max_inflate: 190,
            min_inflate: 111,
            haggles_per: 4,
            race: 0,
            max_insults: 9,
        },
        Owner {
            name: "Oglign Dragon-Slayer   (Dwarf)      Weaponsmith",
            max_cost: 32000,
            max_inflate: 195,
            min_inflate: 112,
            haggles_per: 4,
            race: 5,
            max_insults: 8,
        },
        Owner {
            name: "Gunnar the Paladin     (Human)      Temple",
            max_cost: 5000,
            max_inflate: 185,
            min_inflate: 110,
            haggles_per: 5,
            race: 0,
            max_insults: 23,
        },
        Owner {
            name: "Mauser the Chemist     (Half-Elf)   Alchemist",
            max_cost: 10000,
            max_inflate: 190,
            min_inflate: 111,
            haggles_per: 5,
            race: 1,
            max_insults: 8,
        },
        Owner {
            name: "Gopher the Great!      (Gnome)      Magic Shop",
            max_cost: 20000,
            max_inflate: 215,
            min_inflate: 113,
            haggles_per: 6,
            race: 4,
            max_insults: 10,
        },
        Owner {
            name: "Lyar-el the Comely     (Elf)        General Store",
            max_cost: 300,
            max_inflate: 165,
            min_inflate: 107,
            haggles_per: 6,
            race: 2,
            max_insults: 18,
        },
        Owner {
            name: "Mauglim the Horrible   (Half-Orc)   Armory",
            max_cost: 3000,
            max_inflate: 200,
            min_inflate: 113,
            haggles_per: 5,
            race: 6,
            max_insults: 9,
        },
        Owner {
            name: "Ithyl-Mak the Beastly  (Half-Troll) Weaponsmith",
            max_cost: 3000,
            max_inflate: 210,
            min_inflate: 115,
            haggles_per: 6,
            race: 7,
            max_insults: 8,
        },
        Owner {
            name: "Delilah the Pure       (Half-Elf)   Temple",
            max_cost: 25000,
            max_inflate: 180,
            min_inflate: 107,
            haggles_per: 6,
            race: 1,
            max_insults: 20,
        },
        Owner {
            name: "Wizzle the Chaotic     (Halfling)   Alchemist",
            max_cost: 10000,
            max_inflate: 190,
            min_inflate: 110,
            haggles_per: 6,
            race: 3,
            max_insults: 8,
        },
        Owner {
            name: "Inglorian the Mage     (Human?)     Magic Shop",
            max_cost: 32000,
            max_inflate: 200,
            min_inflate: 110,
            haggles_per: 7,
            race: 0,
            max_insults: 10,
        },
    ]
});
